DIM OSTR1$(5)
DIM OSTR2$(5)
DIM SHARED ISTR$(5)
DIM SHARED PTVALUE(26)
DIM WPTVALUE(15)
DIM SHARED ALPHA$(26)

DATA A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
FOR I = 1 TO 26
    READ ALPHA$(I)
NEXT I

DATA 9,14,1,16,20,5,10,2,21,17,6,25,12,3,22,18,24,7,13,26,15,11,19,4,23,8
FOR I = 1 TO 26
    READ PTVALUE(I)
NEXT I

DATA "BIBLE","IDYLL","NOISE","GULLY","OBESE"
FOR I = 1 TO 5
    READ OSTR1$(I)
NEXT I

DATA "OBESE","TITHE","INLET","IGLOO","TOWER"
FOR I = 1 TO 5
    READ OSTR2$(I)
NEXT I

FOR I = 1 TO 5
    WPTVALUE(I) = CALCVAL(OSTR1$(5))
NEXT I

FOR I = 6 TO 10
    WPTVALUE(I) = CALCVAL(OSTR2$(5))
NEXT I

FOR I = 1 TO 5
    INPUT "ENTER A WORD: ", ISTR$(I)
NEXT I

FOR I = 11 TO 15
    WPTVALUE(I) = CALCVAL(ISTR$(I))
NEXT I

FOR I = 1 TO 15
    PRINT WPTVALUE(I)
NEXT I



FUNCTION CALCVAL (X$)
FOR i = 1 TO LEN(X$)
    'PRINT MID$(X$, I, 1)
    PLACE$ = MID$(X$, i, 1)
    NUM = 1
    'PRINT ALPHA$(NUM)
    WHILE PLACE$ <> ALPHA$(NUM)
        NUM = NUM + 1
    WEND
    PT = PT + PTVALUE(NUM)
NEXT i
CALCVAL = PT
'PRINT PT
END FUNCTION
